sudo: required
services:
  - docker

before_install:
  - docker build -t oto91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run oto91/react-test npm test -- --coverege

after_success:
  - docker build -t oto91/multi-client ./client
  - docker build -t oto91/multi-nginx ./nginx
  - docker build -t oto91/multi-server ./server
  - docker build -t oto91/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push oto91/multi-client
  - docker push oto91/multi-nginx
  - docker push oto91/multi-server
  - docker push oto91/multi-worker